### ISSUE TITLE
[Feature request] Notification channel groups

### ISSUE THREAD

**Issue by SimpleCreations** [akshit5230/react-native-notification-channels#1]
Thank you for such a great lightweight library!

Though I believe it's missing an API that would allow to group notification channels:
https://developer.android.com/develop/ui/views/notifications/channels#CreateChannelGroup

Would be nice to have it as well.

**Comment by akshit5230** [comment]
Let's hope my new commit helps!

**Comment by SimpleCreations** [comment]
@akshit5230 thank you for releasing the update so quickly!

Though, correct me if I'm wrong, there is still no way to put a newly created notification channel in a particular group, as suggested in the docs
> After you've created a new group, you can call [`setGroup()`](https://developer.android.com/reference/android/app/NotificationChannel#setGroup(java.lang.String)) to associate a new [`NotificationChannel`](https://developer.android.com/reference/android/app/NotificationChannel) object with the group.

I think the best way to solve this would be to add an optional `groupId?: string` to `ChannelInfoType`, and then call `setGroup` when creating a channel if `groupId` is present:
https://github.com/akshit5230/react-native-notification-channels/blob/4700fcc94ea0929a7b183c86c4ad83417a19950b/src/index.ts#L10

Which would also require letting the developer specify `groupId` when creating a channel group:
```diff
- createChannelGroup(groupName: string): Promise<boolean | undefined>;
+ createChannelGroup(groupId: string, groupName: string): Promise<boolean | undefined>;
```
https://github.com/akshit5230/react-native-notification-channels/blob/4700fcc94ea0929a7b183c86c4ad83417a19950b/src/index.ts#L23

**Comment by akshit5230** [comment]
I've pushed the changes but I didn't get time to test them. Will do it later. Let me know if you are able to make it work...

**Comment by SimpleCreations** [comment]
@akshit5230 Thank you so much! LGTM. I'll see tomorrow if it works and get back.

**Comment by SimpleCreations** [comment]
@akshit5230 

Doesn't compile without this change:

```diff
-      if (groupId) {
-        channel.setGroup(groupId)
+      if (groupId != null) {
+        channel.group = groupId
```
https://github.com/akshit5230/react-native-notification-channels/blob/0ba8fd73ac9e74f8d2c9df86a344bb15bbfe8119/android/src/main/java/com/reactnativenotificationchannels/NotificationChannelsModule.kt#L90

The method throws an exception if passing `void` to `promise.resolve`; plus I added a check for the Android version as with the other methods:
```diff
  @ReactMethod
  fun createChannelGroup(groupId: String?, groupName: String?, promise: Promise) {
+    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
+      promise.resolve(null)
+      return
+    }
-    promise.resolve(notificationManager.createNotificationChannelGroup(NotificationChannelGroup(groupId, groupName)))
+    notificationManager.createNotificationChannelGroup(NotificationChannelGroup(groupId, groupName))
+    promise.resolve(true)
  }
```
https://github.com/akshit5230/react-native-notification-channels/blob/0ba8fd73ac9e74f8d2c9df86a344bb15bbfe8119/android/src/main/java/com/reactnativenotificationchannels/NotificationChannelsModule.kt#L114

**Comment by SimpleCreations** [comment]
@akshit5230 hi! I'm looking forward to seeing these changes in the repo and hopefully on npm. Please let me know if there's anything I can help with. If it saves you time, I can submit a PR with the changes above.

**Comment by akshit5230** [comment]
Done :) @SimpleCreations
